redirect error message output to stderr in invalidOption function

diff --git a/parus b/parus
--- a/parus
+++ b/parus
@@ -81,7 +81,8 @@ EOF
 }
 
 invalidOption() {
-    echo -e "\033[1mError:\033[0m Invalid option. Use '$(basename "$0") -h' for help."
+    echo -e "\033[1mError:\033[0m Invalid option." \
+    "Use '$(basename "$0") -h' for help." >&2
     exit 2
 }
 
