add error handling

diff --git a/parus b/parus
--- a/parus
+++ b/parus
@@ -4,11 +4,16 @@ skim="sk --ansi --multi --tiebreak=length --preview 'paru --color=always -Si {1}
 --preview-window=right:60% --inline-info --bind 'tab:toggle' --color=pointer:white"
 
 install() {
-    $2 -Sl --color=always |\
+    errorMsg=$(mktemp -u)
+    paru -Sl --color=always 2> $errorMsg |\
     awk '{if (NF > 3) {$4 = "\033[1;33m* ";} print $2, $4 $1;}' |\
     eval "$skim" -p="$1:" |\
     awk '{print $NF "/" $1}' |\
-    xargs -ro paru -S
+    xargs -ro paru -S || echo
+    [ -s $errorMsg ] &&\
+    cat $errorMsg &&\
+    echo -e "\n\033[1mError:\033[0m Paru is not functioning properly. Please check your connection."
+    rm -f $errorMsg
 }
 
 query() {
@@ -19,12 +24,16 @@ query() {
 }
 
 upgrade() {
-    paru -Sy || exit 6
-    upgradablePackages=$(paru -Qu --color=always)
-    [ -z "$upgradablePackages" ] &&\
-    echo -e "\033[1m:: There is no upgradable package :)\033[0m" && exit 0
-    echo "$upgradablePackages" |\
-    eval "$skim" -p="$1:" |\
+    paru -Sy 2> /dev/null
+    [ $? -ne 0 ] &&\
+    echo -e "\033[1mError:\033[0m Updating the package databases failed." && exit 6
+    echo -e "\033[1m:: Checking for upgradable packages...\033[0m"
+    pkgs=$(paru -Qu --color=always 2> /dev/null)
+    pkgsCount=$(wc -l <<< "$pkgs")
+    [ -z "$pkgs" ] &&\
+    echo " there is no upgradable package" && exit 0
+    echo " listed $pkgsCount package$( [ "$pkgsCount" -eq 1 ] || echo s )"
+    eval "$skim" -p="$1:" <<< $pkgs |\
     awk '{print $1}' |\
     xargs -ro paru -S --needed
 }
@@ -59,7 +68,7 @@ EOF
 }
 
 invalidOption() {
-    echo "Error: Invalid option. Use '$(basename "$0") -h' for help."
+    echo -e "\033[1mError:\033[0m Invalid option. Use '$(basename "$0") -h' for help."
     exit 2
 }
 
